name: ECR Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Install Dependancies
      run: |
        pip install -r requirements.txt

    - name: Code Validation
      run: |
        flake8 app.py
    
    - name: Run Code Unittest
      run: |
        export DB_URI=${{ secrets.DB_URI }}
        python -m unittest test_app.py

    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.4'
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        make build
    
    - name: Update  Kube Config
      run: aws eks update-kubeconfig --name developeriq_eks --region ap-southeast-1
    
    - name: Deploy
      run: |
        make deploy
  
